INFO = """# Smiley-App
Smiley-Geschwindigkeitsanzeigen sind ein innovatives Instrument zur Erhöhung der Verkehrssicherheit. Diese Anzeigen wechseln zwischen der angezeigten Geschwindigkeit und einem Smiley-Symbol, das entweder Lob (für Einhalten des Tempolimits) oder Tadel (bei Überschreitung) ausdrückt. Dies geschieht auf eine nicht-bestrafende, freundliche Art und Weise. Seit Anfang Februar 2023 sind 20 solcher neuen Geräte im Einsatz. Sie zeichnen sich durch ihre flexible Einsetzbarkeit und batteriebetriebene Stromversorgung aus, wodurch sie an verschiedenen Orten aufgestellt werden können. Bei der Auswahl der Standorte, insgesamt 75 an der Zahl, lag der Fokus besonders auf sensiblen Bereichen wie Kindergärten, Schulen und Altersheimen. Diese Standorte wurden nach einer umfassenden Evaluation unter Einbeziehung von Fachleuten aus der Kantonsverwaltung und Rückmeldungen aus der Bevölkerung festgelegt. Die 20 Smiley-Geschwindigkeitsanzeigen rotieren zwischen den 75 Standorten und werden an jedem Ort für etwa fünf Monate aufgestellt. Das besondere an ihrem Einsatz: Zunächst messen sie für einen Monat die Geschwindigkeit, ohne dass die Anzeige aktiviert ist. Ab März 2023 sind die Anzeigen für drei Monate eingeschaltet, um dann im letzten Monat erneut ohne aktive Anzeige zu messen. Dieses Muster wird bei zukünftigen Einsätzen beibehalten, um die Effektivität der Anzeigen zu bewerten.

**Nutzung der Daten für Verkehrssicherheitsmassnahmen**

Die während dieser Zeit gesammelten Daten dienen als wichtige Grundlage für Massnahmen zur Erhöhung der Verkehrssicherheit. [Mehr Informationen finden Sie in der Medienmitteilung des JSD des Kantons Basel-Stadt.](https://www.jsd.bs.ch/nm/2023-start-des-betriebs-der-neuen-praeventiven-smiley-geschwindigkeitsanzeigen---ab-maerz-2023-aktiv-jsd.html)

**Datenaufbereitung und Ausreisser-Werte**

Die Rohdaten, die von diesen Geräten gesammelt wurden, sind öffentlich zugänglich auf dem [OGD-Portal](https://data.bs.ch/explore/dataset/100268) des Kantons Basel-Stadt. Bei der Durchsicht dieser Daten fällt auf, dass einige unrealistisch hohe Geschwindigkeiten, wie z.B. 231 km/h in einer 20 km/h-Zone, gemessen wurden. Solche Werte können vor allem bei der graphischen Darstellung stören. Um solche Ausreisser zu bereinigen, wurden statistische Methoden angewendet: Für jede Messstation wurde der Z-Wert, ein Mass für die Abweichung vom Durchschnitt, berechnet. Alle Messungen, deren Z-Wert grösser als 3 oder kleiner als -3 war, wurden aus den Daten entfernt. Diese Methode gewährleistet, dass nur realistische Werte in der Analyse berücksichtigt werden. Dadurch wurden etwa 0.3% der Daten als Ausreisser identifiziert und entfernt. Es ist wichtig zu verstehen, dass ein Z-Wert von -3 oder 3 weit ausserhalb des normalen Bereichs liegt – das entspricht den extremsten 0,3% aller Werte. Diese statistische Filterung hilft dabei, die Daten realitätsgetreu und aussagekräftig zu halten.

Diese Art der Datenbereinigung ist ein wichtiger Schritt, um sicherzustellen, dass die Analysen und daraus abgeleiteten Massnahmen zur Verkehrssicherheit auf zuverlässigen und repräsentativen Daten basieren.
"""

STAT_TEXT = "An den selektierten Stationen wurden insgesamt {0} Messungen durchgeführt. Bei {1} von {2} Standorten ging die Anzahl der Geschwindkeitsüberschreitungen im Betrieb zurück. Bei {3} Standorten nahm die Anzahl der Geschwindkeitsüberschreitungen bei der Ausfahrt gegenüber der Einfahrt ab. Während der Vormessungs- und Nachmessungs-Phase betrug der prozentuale Anteil der Geschwindigkeits-Zunahmen im Durchschnitt {4} %."
